### ISSUE TITLE
Conseguir conxunto de dados

### ISSUE THREAD

**Issue by tomasalmeida** [fanequinha/cerebro#1]
O obxectivo é reunir o maior conxunto de imáxenes grabadas a bordo de embarcacións posible. O ideal sería que os datos inclúan algún tipo de anotación (caixas arredor dos barcos ou a liña do horizonte) ademáis da imaxe/video.

Podemos comezar engadindo en comentarios diferentes datasets que atopemos por ahí.

**Comment by daavoo** [comment]
- Singapore Maritime Dataset(SMD)

Conxunto de vídeos con anotacións para as caixas dos barcos e da liña de horizonte.

Link: https://sites.google.com/site/dilipprasad/home/singapore-maritime-dataset

**Comment by jcleira** [comment]
[Added to `mastermind` README](https://github.com/fanequinha/cerebro/tree/master/mastermind)
