### ISSUE TITLE
Upgrade commander to Python3

### ISSUE THREAD

**Issue by daavoo** [fanequinha/cerebro#30]
The only reason why commander is currently using Python2 is the dependency [`dronekit`](https://github.com/dronekit/dronekit-python)
It [looks like](https://github.com/dronekit/dronekit-python/issues/484#issuecomment-452424209) the latest dronekit's git master (not avaialble in pypi) is fully compatible with Python3 so I think that we should upgrade commander and use that version.

**Comment by nagendra092918** [comment]
how we can use Dronekit python on python3 can u please explain
