### ISSUE TITLE
Dejar configurada una wifi para conexión automática

### ISSUE THREAD

**Issue by tomasalmeida** [fanequinha/cerebro#32]
- [x] Conectarse o lanzar una red wifi al iniciarse
- [x] documentar como conectarse

**Comment by dpmilian** [comment]
Establecida unha nova configuración de rede para a rpi de fanequinha:

- **eth0** -> configurada con IP estática 10.1.2.33

- **wlan0** -> Punto de Acceso WiFi, con IP estática 10.1.3.1:
```
SSID: Fanequinha
pass: fanequinha2k19
(protocolo: 802.11g, canal: 7)

```
Está configurado o enrutado/ NAT entre a wlan e eth0, de forma que se conectamos o cable de rede a un router con acceso a Internet (na sede ou un módem 3G, por exemplo) tería acceso a Internet, tanto a propia rPI como os equipos que se conecten á WiFi Fanequinha.

Tamén a **contraseña do usuario "pi"** está cambiada (me molesta a mensaxe que sae se non a cambias). A pass actual é "**fnqpi**"
