### ISSUE TITLE
Estudar dronekit

### ISSUE THREAD

**Issue by tomasalmeida** [fanequinha/cerebro#4]
Ver https://github.com/ArduPilot/pymavlink

ver que dados recebe e que ten que enviar

**Comment by alexhermida** [comment]
Comenta David Perez que http://python.dronekit.io/ es lo que podemos usar, es una capa de alto nivel que abstrae del protocolo mavlink.

**Comment by jcleira** [comment]
We already have selected dronekit as starting point, and we've started using it on `commander`
